name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Show go version
        run: go version

      - name: Run unit tests
        run: go test ./... -cover
    
  style:
    name: Check formatting
    runs-on: ubuntu-latest

    steps:
      - name: Check formatting
        run: test -z $(go fmt ./...)